### ISSUE TITLE
--external doesn't seem to work.

### ISSUE THREAD

**Issue by zmitry** [evanw/esbuild#65]
I tried to run esbuild on my project with command like that
```
 esbuild  --external:'react-dom'  --platform=node src/index.ts --bundle '--define:process.env.NODE_ENV="development"' --outfile=./dist/storyui.js
```
And I've got this error
```
panic: Internal error

goroutine 233 [running]:
esbuild/bundler.(*Bundle).extractImportsAndExports(0xc00009a180, 0xc000676000, 0x64, 0x69, 0xc000509c80, 0x4, 0xc00037e000, 0x64, 0x64, 0xc000083c10)
        /Users/evan/dev/esbuild/src/esbuild/bundler/bundler.go:657 +0x2d92
esbuild/bundler.(*Bundle).bindImportsAndExports(0xc00009a180, 0xc00070a000, 0xc000676000, 0x64, 0x69, 0xc000509c80, 0xc0004f6000, 0x36, 0x36, 0xc00037e000, ...)
        /Users/evan/dev/esbuild/src/esbuild/bundler/bundler.go:880 +0x19f
esbuild/bundler.(*Bundle).compileBundle.func1(0xc00009a180, 0xc00070a000, 0xc000676000, 0x64, 0x69, 0xc000509c80, 0xc00037e000, 0x64, 0x64, 0xc00027b180, ...)
        /Users/evan/dev/esbuild/src/esbuild/bundler/bundler.go:1281 +0xbb
created by esbuild/bundler.(*Bundle).compileBundle
        /Users/evan/dev/esbuild/src/esbuild/bundler/bundler.go:1277 +0x36a
```

let me know I'm doing something wrong and what is the right approach.

**Comment by evanw** [comment]
Thanks for the report. It looks like I only checked that it works for CommonJS imports (i.e. `require('react-dom')`) but not ES6 imports (i.e. `import 'react-dom'`).

**Comment by zmitry** [comment]
@evanw I've also got another issue but I'm not sure what would be proper report for it. I tried to import output from this library into create-react-app and it says I'm not sure what it means but I bet it should be fixed with es output instead of common js
```
critical dependency: the request of a dependency is an expression
```

**Comment by evanw** [comment]
> critical dependency: the request of a dependency is an expression

It looks like that's because I'm generating code that calls `require` indirectly instead of calling it directly. This was added to support `--external`. I'll have to rework my approach so that `require` is called directly to avoid this. Thanks for calling this to my attention. It should be something I can fix.

**Comment by evanw** [comment]
> I'm not sure what it means but I bet it should be fixed with es output instead of common js

I think this should actually work fine with CommonJS output. At least a basic test of importing a bundle created with esbuild into a create-react-app project now works. The reason why this didn't work before is because the output of esbuild was actually in IIFE (immediately-invoked function expression) format, not CommonJS format. I added the ability to output to CommonJS and made it the default behavior with `--platform=node`.

**Comment by hjlld** [comment]
still not working on v0.2.9.

main.js
```
import { WebGLRenderer, Scene, PerspectiveCamera, Color, Vector3, Vector2, Matrix4, AmbientLight, Raycaster } from 'three/build/three.module.js';

```

command:
```
esbuild --name=PanoView --bundle --outfile=./dist/PanoView.js --sourcemap --target=esnext --external:'three' ./src/View/PanoView.js

esbuild --name=PanoView --bundle --outfile=./dist/PanoView.js --sourcemap --target=esnext --external:'three/build/three.module.js' ./src/View/PanoView.js
```

neither command works, `esbuild` still bundle all three.js code into bundle.js without tree-shaking.

**Comment by evanw** [comment]
That's strange, it works for me. When I do that, this is the entire output file:

```js
(() => {
  let __hasOwnProperty = Object.hasOwnProperty;
  let __modules = {};
  let __commonjs;
  let __require = (id) => {
    let module = __modules[id];
    if (!module) {
      module = __modules[id] = {
        exports: {}
      };
      __commonjs[id](module.exports, module);
    }
    return module.exports;
  };
  let __toModule = (module) => {
    if (module && module.__esModule) {
      return module;
    }
    let result = {};
    for (let key in module) {
      if (__hasOwnProperty.call(module, key)) {
        result[key] = module[key];
      }
    }
    result.default = module;
    return result;
  };
  let __import = (id) => {
    return __toModule(__require(id));
  };
  __commonjs = {
    0() {
      // main.js
      const three_module = __toModule(require("three/build/three.module.js"));
    }
  };
  return __require(0);
})();
```

My esbuild command:

```
esbuild --bundle main.js --outfile=out.js --external:three/build/three.module.js
```

Perhaps the shell you're using doesn't like the single quotes around the module name?

**Comment by hjlld** [comment]
I got it, my fault.

because modules are imported from various path of three.js, not only `three/build/three.module.js` but also some modules from 'three/examples/jsm/...'

so i add multiple `--external:` parameter, like:

```
esbuild --name=PanoView --bundle --outfile=./dist/PanoView.js --sourcemap --target=esnext --external:three/build/three.module.js --external:three/examples/jsm/objects/Lensflare.js --external:three/examples/jsm/loaders/BasisTextureLoader.js  ./src/View/PanoView.js
```

now, it works!

so could this `--external` parameter accept a regexp or would it recursively exclude children path under 'three'?

Thank you!

**Comment by eric-burel** [comment]
Hi, I am hitting a similar issue, treating React as external will generate a `require()` call, which is however not accepted by Next.js server-side. Is it an error from Next.js side? 
```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/code/npm-the-right-way/demo-next-app/node_modules/my-package-esbuild/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

More broadly I struggle to have an Esbuild demo for Next.js covering server, client and shared code

Reproduction here: https://github.com/VulcanJS/npm-the-right-way
